=== zaned897/cortex_LR_team/LOSSRUNS/app/test/resources/schemas/data_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "license": {
      "type": "string"
    },
    "npi": {
      "type": "string"
    },
    "dcn": {
      "type": "string"
    },
    "entity_name": {
        "type": "string"
    },
    "practitioner_name": {
      "type": "string"
    },
    "action_initial": {
      "type": "string"
    },
    "action_basis": {
      "type": "string"
    },
    "event_outcome": {
    "type": "string"
    },
    "process_date": {
    "type": "string"
    },
    "payment_date": {
    "type": "string"
    },
    "event_day": {
    "type": "string"
    },
    "amount_pract": {
    "type": "string"
    },
    "payment_total_amount": {
    "type": "string"
    }
  },
  "required": [
    "license",
    "npi",
    "dcn",
    "entity_name",
    "practitioner_name",
    "action_initial",
    "action_basis",
    "event_outcome",
    "process_date",
    "payment_date",
    "event_day",
    "amount_pract",
    "payment_total_amount"
  ]
}

=== zaned897/cortex_LR_team/test/resources/expected_data/NPDBQA3.json
[
  {
    "license": "'PA04912, TX'",
    "npi": "1972719151",
    "dcn": "5500000069864162",
    "entity_name": "'THE MEDICAL PROTECTIVE COMPANY', 'THE MEDICAL PROTECTIVE COMPANY'",
    "practitioner_name": "'RICKERT, JEFF C'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'FAILURE TO DIAGNOSE'",
    "event_outcome": "'DEATH (09)'",
    "process_date": "08/02/2011",
    "payment_date": "07/21/2011",
    "event_day": "08/18/2010",
    "amount_pract": "240000",
    "payment_total_amount": "240000"
  }
]

=== zaned897/cortex_LR_team/LOSSRUNS/app/test/resources/expected_data/NPDBQA7.json
[
  {
    "license": "'217720, NY'",
    "npi": "1720069438",
    "dcn": "5500000131130824",
    "entity_name": "'PHYSICIANS RECIPROCAL INSURERS'",
    "practitioner_name": "'ALASTRA, ANTHONY'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'IMPROPER PERFORMANCE'",
    "event_outcome": "'SIGNIFIGANT PERMANENT INJURY (06)'",
    "process_date": "01/24/2018",
    "payment_date": "01/16/2018",
    "event_day": "02/09/2011",
    "amount_pract": "1000000",
    "payment_total_amount": "1000000"
  },
  {
    "license": "'217720, NY'",
    "npi": "1720069438",
    "dcn": "5500000111410130",
    "entity_name": "'PHYSICIANS RECIPROCAL INSURERS'",
    "practitioner_name": "'ALASTRA, ANTHONY'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'FAILURE TO DIAGNOSE'",
    "event_outcome": "'SIGNIFIGANT PERMANENT INJURY (06)'",
    "process_date": "08/24/2016",
    "payment_date": "8/24/2016",
    "event_day": "11/30/2011",
    "amount_pract": "75000",
    "payment_total_amount": "75000"
  },
  {
    "license": "'217720, NY'",
    "npi": "1720069438",
    "dcn": "5500000093021355",
    "entity_name": "'APPLIED MEDICO-LEGAL SILUTIONS RRG'",
    "practitioner_name": "'ALASTRA, ANTHONY'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'IMPROPER PERFORMANCE'",
    "event_outcome": "'MINOR TEMPORARY INJURY (03)'",
    "process_date": "11/06/2014",
    "payment_date": "9/29/2014",
    "event_day": "03/04/2009",
    "amount_pract": "175000",
    "payment_total_amount": "175000"
  },
  {
    "license": "'217720, NY'",
    "npi": "1720069438",
    "dcn": "5500000085019114",
    "entity_name": "'PHYSICIANS RECIPROCAL INSURERS'",
    "practitioner_name": "'ALASTRA, ANTHONY'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'FAILURE TO RECOGNIZE A COMPLICATION','FAILURE TO TREAT'",
    "event_outcome": "'DEATH (09)'",
    "process_date": "10/09/2013",
    "payment_date": "09/05/2013",
    "event_day": "05/09/2008",
    "amount_pract": "950000",
    "payment_total_amount": "950000"
  },
  {
    "license": "'217720, NY'",
    "npi": "1720069438",
    "dcn": "5500000076340126",
    "entity_name": "'PHYSICIANS RECIPROCAL INSURERS'",
    "practitioner_name": "'ALASTRA, ANTHONY'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'FAILURE TO ORDER APPROPRIATE TEST'",
    "event_outcome": "'SIGNIFIGANT PERMANENT INJURY (06)'",
    "process_date": "07/25/2012",
    "payment_date": "07/23/2012",
    "event_day": "12/19/2005",
    "amount_pract": "750000",
    "payment_total_amount": "750000"
  },
  {
    "license": "'217720, NY'",
    "npi": "1720069438",
    "dcn": "5500000070612211",
    "entity_name": "'PHYSICIANS RECIPROCAL INSURERS'",
    "practitioner_name": "'ALASTRA, ANTHONY'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'FAILURE TO RECOGNIZE A COMPLICATION'",
    "event_outcome": "'DEATH (09)'",
    "process_date": "09/14/2011",
    "payment_date": "08/01/2011",
    "event_day": "03/20/2006",
    "amount_pract": "500000",
    "payment_total_amount": "500000"
  }
]

=== zaned897/cortex_LR_team/test/resources/expected_data/NPDBQA15.json
[
    {
        "license": "321149, UT', 'MD60230696, WA'", 
        "npi": "'1104987916'", 
        "dcn": "'5500000153184263'",
        "entity_name": "'UMIA INSURANCE INC'",
        "practitioner_name": "'KAMALU,'",
        "action_initial": "'SETTLEMENT'",
        "action_basis": "'FAILURE TO TEST EQUIPMENT'",
        "event_outcome": "' MINOR TEMPORARY INJURY (03)'",
        "process_date": "'10/29/2015'",
        "payment_date": "'10/21/2015'",
        "event_day": "'01/06/2008'",
        "amount_pract": "'5000'",
        "payment_total_amount": "'5000'"
    }, 
    {
        "license": "321149, UT', 'MD60230696, WA'", 
        "npi": "'1104987916'", 
        "dcn": "'5500000101038064'",
        "entity_name": "'UTAH MEDICAL INSURANCE ASSN', 'UMIA INSURANCE INC'",
        "practitioner_name": "'KAMALU, LAYNE K'",
        "action_initial": "'SETTLEMENT'",
        "action_basis": "'FAILURE TO ORDER APPROPRIATE TEST'", 
        "event_outcome": "' MINOR PERMANENT INJURY (05)'",
        "process_date": "'06/06/2007'",
        "payment_date": "'06/05/2007'",
        "event_day": "'05/19/2005'",
        "amount_pract": "'40000'",
        "payment_total_amount": "'212500'"
        }
    ]

=== zaned897/cortex_LR_team/test/resources/expected_data/NPDBIP.json
[
    {
        "license": "R19344, NM', 'AP7678, AZ'", 
        "npi": "'1780676700'", 
        "dcn": "'5500000162601705'",
        "entity_name": "'AMERICAN CASUALTY CO OF READING PA', 'AMERICAN CASUALTY CO OF READING PENNSYLVANIA'", 
        "practitioner_name": "'SISNEROS, ALICE'", 
        "action_initial": "'SETTLEMENT'", 
        "action_basis": "'FAILURE TO RECOGNIZE COMPLICATION', 'FAILURE TO DIAGNOSE'", 
        "event_outcome": "' DEATH (09)'", 
        "process_date": "'04/29/2009'", 
        "payment_date": "'04/08/2009'", 
        "event_day": "'10/28/2007'",
        "amount_pract": "'1000000'",
        "payment_total_amount": "'1000000'"
    }]

=== zaned897/cortex_LR_team/LOSSRUNS/app/test/resources/expected_data/NPDBQA2.json
[
  {
    "license": "0S9841, FL', ' 4835, AZ'",
    "npi": "1831199983",
    "dcn": "5500000132501118",
    "entity_name": "'LEXINGTON INSURANCE COMPANY', 'LEXINGTON INSURANCE COMPANY'",
    "practitioner_name": "'BERECZKI, ZOLTAN JR', 'LASER SPINE INSTITUTE'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'IMPROPERLY PERFORMED TEST'",
    "event_outcome": "'MINOR PERMANENT INJURY (05)'",
    "process_date": "08/16/2013",
    "payment_date": "05/15/2013",
    "event_day": "10/21/2008",
    "amount_pract": "244622",
    "payment_total_amount": "244622"
  },
  {
    "license": "'0S9841, FL', ' 4835, AZ', '0S9841, PA'",
    "npi": "1831199983",
    "dcn": "5500000083945866",
    "entity_name": "'LASER SPINE INSTITUTE', 'LASER SPINE INSTITUTE LLC'",
    "practitioner_name": "'BERECZKI, ZOLTON JR', 'LASER SPINE INSTITUTE'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'IMPROPER PERFORMANCE'",
    "event_outcome": "'MINOR PERMANENT INJURY (05)'",
    "process_date": "05/17/2013",
    "payment_date": "05/14/2013",
    "event_day": "10/21/2008",
    "amount_pract": "155377",
    "payment_total_amount": "155377"
  },
  {
    "license": "'0S9841, FL', ' 4835, AZ', '0S9841, PA'",
    "npi": "1831199983",
    "dcn": "5500000082199846",
    "entity_name": "'LEXINGTON INSURANCE COMPANY', 'LEXINGTON INSURANCE COMPANY'",
    "practitioner_name": "'BERECZKI, ZOLTAN JR', 'LASER SPINE INSTITUTE'",
    "action_initial": "'SETTLEMENT'",
    "action_basis": "'WRONG PROCEDURE OR TREATMENT'",
    "event_outcome": "'MINOR PERMANENT INJURY (05)'",
    "process_date": "10/18/2012",
    "payment_date": "06/20/2012",
    "event_day": "10/12/2010",
    "amount_pract": "150000",
    "payment_total_amount": "650000"
  }
]
